 CREATE TABLE "ANIMAL"."MEMBERS" 
   (	"IDX" NUMBER(8,0) NOT NULL ENABLE, 
	"RRN2" CHAR(7 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"USERID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PWD" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"HP1" CHAR(3 BYTE) NOT NULL ENABLE, 
	"HP2" CHAR(4 BYTE) NOT NULL ENABLE, 
	"HP3" CHAR(4 BYTE) NOT NULL ENABLE, 
	"POST" CHAR(5 BYTE), 
	"ADDR1" VARCHAR2(100 BYTE), 
	"ADDR2" VARCHAR2(100 BYTE), 
	"INDATE" DATE, 
	"STATUS" NUMBER(2,0), 
	"NICK" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"RRN1" CHAR(6 BYTE) NOT NULL ENABLE, 
	"MAIL" VARCHAR2(100 BYTE), 
	 CONSTRAINT "PK_MEMBERS" PRIMARY KEY ("IDX", "RRN2")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."IDX" IS '회원번호';
   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."RRN2" IS '주민번호2';
   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."NAME" IS '이름';
   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."USERID" IS '아이디';
   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."PWD" IS '비밀번호';
   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."HP1" IS '연락처1';
   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."HP2" IS '얀락처2';
   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."HP3" IS '연락처3';
   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."POST" IS '우편번호';
   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."ADDR1" IS '주소1';
   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."ADDR2" IS '주소2';
   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."INDATE" IS '가입일';
   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."STATUS" IS '회원상태';
   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."NICK" IS '닉네임';
   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."RRN1" IS '주민번호1';
   COMMENT ON COLUMN "ANIMAL"."MEMBERS"."MAIL" IS '이메일';
   COMMENT ON TABLE "ANIMAL"."MEMBERS"  IS '회원';



